apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-config-with
  namespace: default
data:
{{- with .Values.encargados }}
  {{- range . }}
    Encargado: {{.}}
  {{- end }}
{{- end}}
